Repository fitculator-ai/Team2_FE_B2B, pull requests merged in 2025-02, with the labels that each got.

#33 [bugfix] build 오류 수정
  .env
  .gitignore
  src/app/layout.tsx
  src/components/Layout/Navbar.tsx
  src/components/Swiper/Swiper.tsx
  src/components/Swiper/Team/Team.tsx
Labels: 🧨 HotFix

#36 [생성, 수정] 서브페이지, text_logo 아이콘
  public/image/logo_text.webp
  public/image/person.webp
  src/app/page.tsx
  src/components/Card/AboutCard.tsx
  src/components/Layout/Navbar.tsx
  src/components/SpeechBubble.tsx
  src/sections/AboutBanner.tsx
  src/sections/SubBannerSection.tsx
  src/styles/icons.css
Labels: ✨ Feat, 🛠 Fix

#37 [생성] 메인페이지
  public/image/bg_main.webp
  src/app/page.tsx
  src/sections/MainSection.tsx
  src/sections/StatisticsSection.tsx
Labels: ✨ Feat

#38 [스타일] 반응형 구현
  package.json
  pnpm-lock.yaml
  public/svg/process.svg
  public/svg/process_diagram.svg
  src/components/Accordion.tsx
  src/components/ContactUsSection.tsx
  src/components/FAQSection.tsx
  src/components/Form.tsx
  src/components/Icon/Icon.tsx
  src/components/ProcessSection.tsx
  src/components/ProcessStep.tsx
  tailwind.config.ts
Labels: 🎨 Design

#40 [기능] Swiper 성능 개선
  src/components/Swiper/Review/Review.tsx
  src/components/Swiper/Solution/Solution.tsx
  src/components/Swiper/Swiper.tsx
Labels: ✨ Feat

#43 [수정] 내용 추가, 반응형 여백 수정
  src/components/Button.tsx
  src/components/Card/AboutCard.tsx
  src/components/Form.tsx
  src/components/Layout/Navbar.tsx
  src/components/Layout/SectionLayout.tsx
  src/sections/AboutSection.tsx
  src/sections/ContactUsSection.tsx
  src/sections/StatisticsSection.tsx
  src/sections/TeamInfoSection.tsx
Labels: 🛠 Fix
